#ifndef NOTES_H
#define NOTES_H

class Notes 
{
public:
    static float B4;
    static float A0;     
    static float AsBb0;
    static float B;     
    static float C1;   
    static float CsDb1;  
    static float D1;    
    static float DsEb1;  
    static float E1;    
    static float F1;    
    static float FsGb1;  
    static float G1;     
    static float GsAb1;  
    static float A1;     
    static float AsBb1;  
    static float B1;     
    static float C2;  
    static float CsDb2;  
    static float D2; 
    static float DsEb2;  
    static float E2;    
    static float F2;    
    static float FsGb2;  
    static float G2;     
    static float GsAb2; 
    static float A2;    
    static float AsBb2; 
    static float B2;     
    static float C3;     
    static float CsDb3;  
    static float D3;    
    static float DsEb3;  
    static float E3;    
    static float F3;    
    static float FsGb3;  
    static float G3;     
    static float GsAb3;  
    static float A3;     
    static float AsBb3;  
    static float B3;     
    static float C4;     
    static float CsDb4;  
    static float D4;    
    static float DsEb4;  
    static float E4;    
    static float F4;    
    static float FsGb4;  
    static float G4;     
    static float GsAb4;  
    static float A4;     
    static float AsBb4;  
    static float B4;     
    static float C5;     
    static float CsDb5;  
    static float D5;    
    static float DsEb5; 
    static float E5;    
    static float F5;    
    static float FsGb5;  
    static float G5;     
    static float GsAb5;  
    static float A5;     
    static float AsBb5;  
    static float B5;     
    static float C6;     
    static float CsDb6;  
    static float D6;    
    static float DsEb6;  
    static float E6;    
    static float F6;    
    static float FsGb6;  
    static float G6;     
    static float GsAb6; 
    static float A6;     
    static float AsBb6; 
    static float B6;     
    static float C7;     
    static float CsDb7;  
    static float D7;    
    static float DsEb7;  
    static float E7;    
    static float F7;    
    static float FsGb7;  
    static float G7;     
    static float GsAb7;  
    static float A7;     
    static float AsBb7;  
    static float B7;     
    static float C8;     
};

#endif
